"""
NSE Stock Universe — 572 Validated Symbols
Auto-cleaned: Only symbols confirmed as active on NSE (via Angel One)
Last updated: 2026-03-27
"""

STOCK_UNIVERSE = [
    "RELIANCE", "TCS", "HDFCBANK", "INFY", "ICICIBANK", "HINDUNILVR", "SBIN", "BHARTIARTL",
    "KOTAKBANK", "ITC", "LT", "AXISBANK", "BAJFINANCE", "ASIANPAINT", "MARUTI", "HCLTECH",
    "SUNPHARMA", "TITAN", "WIPRO", "ULTRACEMCO", "NTPC", "POWERGRID", "NESTLEIND", "TECHM",
    "ONGC", "TATASTEEL", "JSWSTEEL", "INDUSINDBK", "HINDALCO", "ADANIENT", "ADANIPORTS", "BAJAJFINSV",
    "GRASIM", "CIPLA", "DRREDDY", "COALINDIA", "BPCL", "EICHERMOT", "DIVISLAB", "BRITANNIA",
    "APOLLOHOSP", "HEROMOTOCO", "SBILIFE", "DABUR", "HDFCLIFE", "BAJAJ-AUTO", "TATACONSUM", "PIDILITIND",
    "SIEMENS", "ADANIGREEN", "HAVELLS", "AMBUJACEM", "DLF", "GODREJCP", "TRENT", "VEDL",
    "BANKBARODA", "IOC", "ICICIPRULI", "INDIGO", "ABB", "SRF", "NAUKRI", "TORNTPHARM",
    "GAIL", "PIIND", "HINDPETRO", "MARICO", "PERSISTENT", "TATAPOWER", "COLPAL", "CANBK",
    "BERGEPAINT", "MPHASIS", "PFC", "RECLTD", "IDFCFIRSTB", "LUPIN", "AUROPHARMA", "VOLTAS",
    "POLYCAB", "SHREECEM", "TVSMOTOR", "SAIL", "MRF", "SOLARINDS", "FEDERALBNK", "CUMMINSIND",
    "CONCOR", "PETRONET", "ABCAPITAL", "NMDC", "LALPATHLAB", "JUBLFOOD", "MFSL", "OBEROIRLTY",
    "COFORGE", "ALKEM", "ASTRAL", "MAXHEALTH", "OFSS", "IRCTC", "CROMPTON", "BHARATFORG",
    "LICHSGFIN", "AUBANK", "IPCALAB", "DEEPAKNTR", "DIXON", "ESCORTS", "BIOCON", "BALKRISIND",
    "LTTS", "LAURUSLABS", "KPITTECH", "SYNGENE", "BEL", "ATUL", "DELHIVERY", "SUPREMEIND",
    "PAGEIND", "HINDCOPPER", "PHOENIXLTD", "NATCOPHARM", "NAVINFLUOR", "ZYDUSLIFE", "UBL", "RAMCOCEM",
    "TATAELXSI", "APLAPOLLO", "BATAINDIA", "THERMAX", "SUNDARMFIN", "SUNTV", "MUTHOOTFIN", "HONAUT",
    "WHIRLPOOL", "IDEA", "M&MFIN", "YESBANK", "MANAPPURAM", "GUJGASLTD", "AAVAS", "IEX",
    "JKCEMENT", "NATIONALUM", "SONACOMS", "RATNAMANI", "CARBORUNIV", "METROPOLIS", "FORTIS", "KAJARIACER",
    "RELAXO", "GRINDWELL", "ENDURANCE", "FINEORG", "AJANTPHARM", "KANSAINER", "SUMICHEM", "REDINGTON",
    "JBCHEPHARM", "CASTROLIND", "EMAMILTD", "APLLTD", "CHOLAFIN", "PGHH", "TIMKEN", "GLAXO",
    "CUB", "NIACL", "VGUARD", "PRESTIGE", "STARHEALTH", "ABSLAMC", "CLEAN", "HAL",
    "BDL", "MAZDOCK", "NHPC", "SJVN", "IRFC", "PAYTM", "JSWENERGY", "JSL",
    "AFFLE", "ZEEL", "ABFRL", "GODREJPROP", "CANFINHOME", "CHAMBLFERT", "SAPPHIRE", "GALAXYSURF",
    "IIFL", "CESC", "SPARC", "MOTILALOFS", "ANGELONE", "CGPOWER", "KAYNES", "LLOYDSME",
    "PNBHOUSING", "HUDCO", "SUZLON", "PVRINOX", "FLUOROCHEM", "BLUEDART", "GRINFRA", "DATAPATTNS",
    "ZENSARTECH", "CAMPUS", "NYKAA", "DMART", "ATGL", "TATACHEM", "MSUMI", "SUNDRMFAST",
    "TIINDIA", "CYIENT", "HATSUN", "CENTURYPLY", "ROUTE", "GPPL", "RITES", "RVNL",
    "M&M", "TORNTPOWER", "GICRE", "BANKINDIA", "INDIANB", "PNB", "UNIONBANK", "CENTRALBK",
    "IOB", "MAHABANK", "UCOBANK", "BANDHANBNK", "RBLBANK", "IDBI", "CRISIL", "SBICARD",
    "POONAWALLA", "SHRIRAMFIN", "BAJAJHLDNG", "LICI", "TATAINVEST", "JMFINANCIL", "EDELWEISS", "MOTHERSON",
    "BOSCHLTD", "EXIDEIND", "ASHOKLEY", "TITAGARH", "CRAFTSMAN", "GABRIEL", "LUMAXTECH", "SWARAJENG",
    "SUPRAJIT", "SCHAEFFLER", "SKFINDIA", "GLAND", "GLENMARK", "GRANULES", "ABBOTINDIA", "PFIZER",
    "ERIS", "MANKIND", "MEDPLUS", "YATHARTH", "RAINBOW", "VIJAYA", "SUPRIYA", "IOLCP",
    "SOLARA", "CAPLIPOINT", "NEULANDLAB", "SHILPAMED", "AARTIDRUGS", "HIKAL", "ANURAS", "KRSNAA",
    "POLYMED", "GUFICBIO", "MASTEK", "HAPPSTMNDS", "NEWGEN", "INTELLECT", "RATEGAIN", "LATENTVIEW",
    "TANLA", "MAPMYINDIA", "NAZARA", "YATRA", "NIITLTD", "QUICKHEAL", "JUSTDIAL", "GODREJIND",
    "JYOTHYLAB", "BIKAJI", "DEVYANI", "MRPL", "VSTIND", "GODFRYPHLP", "RADICO", "EIDPARRY",
    "ZYDUSWELL", "KRBL", "LTFOODS", "DODLA", "HERITGFOOD", "UFLEX", "VENKEYS", "JUBLPHARMA",
    "WELCORP", "JINDALSTEL", "MOIL", "KIOCL", "SARDAEN", "GALLANTT", "JAMNAAUTO", "NSLNISP",
    "HINDZINC", "MIDHANI", "RSYSTEMS", "MGL", "IGL", "OIL", "CHENNPETRO", "GSPL",
    "ADANIPOWER", "GNFC", "ACC", "HEIDELBERG", "JKLAKSHMI", "NUVOCO", "ORIENTCEM", "GREENPLY",
    "ORIENTBELL", "CERA", "PRINCEPIPE", "NBCC", "IRCON", "PNCINFRA", "AHLUCONT", "NCC",
    "JKIL", "ENGINERSIN", "BLS", "HGINFRA", "GPIL", "BEML", "GRSE", "COCHINSHIP",
    "DCAL", "PARAS", "CENTUM", "ALKYLAMINE", "ROSSARI", "NOCIL", "AARTIIND", "NEOGEN",
    "LXCHEM", "JUBLINGREA", "CHEMPLASTS", "BALAMINES", "HERANBA", "PRIVISCL", "BRIGADE", "SOBHA",
    "MAHLIFE", "SUNTECK", "KOLTEPATIL", "PURVA", "LODHA", "RUSTOMJEE", "SIGNATURE", "TTML",
    "HATHWAY", "GTPL", "SAREGAMA", "SHEMAROO", "TVTODAY", "NDTV", "DEN", "SHOPERSTOP",
    "VMART", "WESTLIFE", "RAYMOND", "ARVIND", "GOKEX", "CELLO", "STOVEKRAFT", "BUTTERFLY",
    "TTKHLTCARE", "BAJAJELEC", "TCI", "ALLCARGO", "MAHLOG", "SNOWMAN", "TRIDENT", "HIMATSEIDE",
    "DONEAR", "NITIRAJ", "SPAL", "RUPA", "LUXIND", "RPOWER", "JPPOWER", "POWERMECH",
    "TNPL", "WSTCSTPAPR", "JKPAPER", "STARPAPER", "HUHTAMAKI", "EPL", "3MINDIA", "TATACOMM",
    "BIRLACORPN", "DCMSHRIRAM", "ZUARI", "HINDWAREAP", "ICICIGI", "POLICYBZR", "GODIGIT", "BALRAMCHIN",
    "TRIVENI", "RENUKA", "DWARKESH", "DHANUKA", "UPL", "RALLIS", "COROMANDEL", "GODREJAGRO",
    "CAMS", "CDSL", "KFINTECH", "UTIAMC", "BSE", "MCX", "IONEXCHANG", "KSOLVES",
    "GOCOLORS", "EASEMYTRIP", "IXIGO", "TRACXN", "IDEAFORGE", "SYRMA", "AVALON", "AMBER",
    "PGEL", "SAGCEM", "JTEKTINDIA", "ASTRAZEN", "NETWORK18", "GESHIP", "INDIGOPNTS", "CEATLTD",
    "APOLLOTYRE", "TEAMLEASE", "QUESS", "SJS", "GRAVITA", "ECLERX", "BSOFT", "TATATECH",
    "SAFARI", "VBL", "CCL", "UJJIVANSFB", "CREDITACC", "SPANDANA", "FUSION", "FINPIPE",
    "ASTEC", "KIRLOSENG", "ELGIEQUIP", "ISGEC", "PRAJIND", "VOLTAMP", "TDPOWERSYS", "HITECHCORP",
    "EMUDHRA", "STLTECH", "AARTIPHARM", "WINDLAS", "FLAIR", "DATAMATICS", "BORORENEW", "INOXWIND",
    "SHYAMMETL", "MAHSEAMLES", "JINDALSAW", "GMDCLTD", "NLCINDIA", "IREDA", "PPLPHARMA", "STARCEMENT",
    "OLECTRA", "KIMS", "THYROCARE", "SBCL", "TEXRAIL", "RAILTEL", "EPIGRAL", "SENCO",
    "CLSEL", "NAVNETEDUL", "SCHAND", "SHALPAINTS", "INDHOTEL", "LEMONTREE", "CHALET", "DOMS",
    "KARURVYSYA", "DCBBANK", "SOUTHBANK", "SURYODAY", "ESAFSFB", "HOMEFIRST", "APTUS", "MASFIN",
    "MARKSANS", "BLISSGVS", "SANOFI", "ORCHPHARMA", "RPSGVENT", "MSTCLTD", "NELCO", "AURIONPRO",
    "NUCLEUS", "SAKSOFT", "ONMOBILE", "AVANTIFEED", "MAHSCOOTER", "VSTTILLERS", "FORCEMOT", "PENIND",
    "LUMAXIND", "STERTOOLS", "SUNFLAG", "GUJALKALI", "KESORAMIND", "CAPACITE", "ASHOKA", "AIAENG",
    "GREAVESCOT", "NESCO", "ELECON", "BASF", "ASAHIINDIA", "VINATIORGA", "SHK", "SYMPHONY",
    "ORIENTELEC", "LAOPALA", "RAJRATAN", "ANANTRAJ", "ARVSMART", "PGIL", "STYL", "GIPCL",
    "TAJGVK", "ORIENTHOT", "DALMIASUG", "GOLDIAM", "KPRMILL", "WOCKPHARMA", "XPROINDIA", "ZFCVINDIA",
    "STEL", "DCXINDIA", "PRECWIRE", "GATEWAY",
]


SECTORS = {
    # Agri (9)
    "BALRAMCHIN": "Agri",
    "RENUKA": "Agri",
    "DWARKESH": "Agri",
    "DHANUKA": "Agri",
    "UPL": "Agri",
    "RALLIS": "Agri",
    "COROMANDEL": "Agri",
    "GODREJAGRO": "Agri",
    "DALMIASUG": "Agri",
    # Auto (34)
    "MARUTI": "Auto",
    "EICHERMOT": "Auto",
    "HEROMOTOCO": "Auto",
    "BAJAJ-AUTO": "Auto",
    "TVSMOTOR": "Auto",
    "MRF": "Auto",
    "ESCORTS": "Auto",
    "BALKRISIND": "Auto",
    "SONACOMS": "Auto",
    "ENDURANCE": "Auto",
    "MSUMI": "Auto",
    "SUNDRMFAST": "Auto",
    "M&M": "Auto",
    "MOTHERSON": "Auto",
    "BOSCHLTD": "Auto",
    "EXIDEIND": "Auto",
    "ASHOKLEY": "Auto",
    "CRAFTSMAN": "Auto",
    "GABRIEL": "Auto",
    "LUMAXTECH": "Auto",
    "SWARAJENG": "Auto",
    "SUPRAJIT": "Auto",
    "SCHAEFFLER": "Auto",
    "SKFINDIA": "Auto",
    "JAMNAAUTO": "Auto",
    "JTEKTINDIA": "Auto",
    "CEATLTD": "Auto",
    "APOLLOTYRE": "Auto",
    "OLECTRA": "Auto",
    "MAHSCOOTER": "Auto",
    "VSTTILLERS": "Auto",
    "FORCEMOT": "Auto",
    "PENIND": "Auto",
    "LUMAXIND": "Auto",
    # Aviation (1)
    "INDIGO": "Aviation",
    # Banking (30)
    "HDFCBANK": "Banking",
    "ICICIBANK": "Banking",
    "SBIN": "Banking",
    "KOTAKBANK": "Banking",
    "AXISBANK": "Banking",
    "INDUSINDBK": "Banking",
    "BANKBARODA": "Banking",
    "CANBK": "Banking",
    "IDFCFIRSTB": "Banking",
    "FEDERALBNK": "Banking",
    "AUBANK": "Banking",
    "YESBANK": "Banking",
    "CUB": "Banking",
    "BANKINDIA": "Banking",
    "INDIANB": "Banking",
    "PNB": "Banking",
    "UNIONBANK": "Banking",
    "CENTRALBK": "Banking",
    "IOB": "Banking",
    "MAHABANK": "Banking",
    "UCOBANK": "Banking",
    "BANDHANBNK": "Banking",
    "RBLBANK": "Banking",
    "IDBI": "Banking",
    "UJJIVANSFB": "Banking",
    "KARURVYSYA": "Banking",
    "DCBBANK": "Banking",
    "SOUTHBANK": "Banking",
    "SURYODAY": "Banking",
    "ESAFSFB": "Banking",
    # Building Materials (10)
    "ASTRAL": "Building Materials",
    "SUPREMEIND": "Building Materials",
    "APLAPOLLO": "Building Materials",
    "RATNAMANI": "Building Materials",
    "KAJARIACER": "Building Materials",
    "CENTURYPLY": "Building Materials",
    "GREENPLY": "Building Materials",
    "ORIENTBELL": "Building Materials",
    "CERA": "Building Materials",
    "PRINCEPIPE": "Building Materials",
    # Cement (13)
    "ULTRACEMCO": "Cement",
    "AMBUJACEM": "Cement",
    "SHREECEM": "Cement",
    "RAMCOCEM": "Cement",
    "JKCEMENT": "Cement",
    "ACC": "Cement",
    "HEIDELBERG": "Cement",
    "JKLAKSHMI": "Cement",
    "NUVOCO": "Cement",
    "ORIENTCEM": "Cement",
    "SAGCEM": "Cement",
    "STARCEMENT": "Cement",
    "KESORAMIND": "Cement",
    # Chemicals (30)
    "PIDILITIND": "Chemicals",
    "SRF": "Chemicals",
    "PIIND": "Chemicals",
    "DEEPAKNTR": "Chemicals",
    "ATUL": "Chemicals",
    "NAVINFLUOR": "Chemicals",
    "FINEORG": "Chemicals",
    "SUMICHEM": "Chemicals",
    "CLEAN": "Chemicals",
    "CHAMBLFERT": "Chemicals",
    "FLUOROCHEM": "Chemicals",
    "TATACHEM": "Chemicals",
    "ALKYLAMINE": "Chemicals",
    "ROSSARI": "Chemicals",
    "NOCIL": "Chemicals",
    "AARTIIND": "Chemicals",
    "NEOGEN": "Chemicals",
    "LXCHEM": "Chemicals",
    "JUBLINGREA": "Chemicals",
    "CHEMPLASTS": "Chemicals",
    "BALAMINES": "Chemicals",
    "HERANBA": "Chemicals",
    "PRIVISCL": "Chemicals",
    "EPIGRAL": "Chemicals",
    "GUJALKALI": "Chemicals",
    "BASF": "Chemicals",
    "ASAHIINDIA": "Chemicals",
    "VINATIORGA": "Chemicals",
    "SHK": "Chemicals",
    "ZFCVINDIA": "Chemicals",
    # Construction (11)
    "LT": "Construction",
    "NBCC": "Construction",
    "IRCON": "Construction",
    "PNCINFRA": "Construction",
    "AHLUCONT": "Construction",
    "NCC": "Construction",
    "JKIL": "Construction",
    "ENGINERSIN": "Construction",
    "HGINFRA": "Construction",
    "CAPACITE": "Construction",
    "ASHOKA": "Construction",
    # Consumer (26)
    "TITAN": "Consumer",
    "JUBLFOOD": "Consumer",
    "PAGEIND": "Consumer",
    "BATAINDIA": "Consumer",
    "WHIRLPOOL": "Consumer",
    "RELAXO": "Consumer",
    "SAPPHIRE": "Consumer",
    "CAMPUS": "Consumer",
    "DEVYANI": "Consumer",
    "WESTLIFE": "Consumer",
    "RAYMOND": "Consumer",
    "GOKEX": "Consumer",
    "CELLO": "Consumer",
    "STOVEKRAFT": "Consumer",
    "BUTTERFLY": "Consumer",
    "TTKHLTCARE": "Consumer",
    "BAJAJELEC": "Consumer",
    "SAFARI": "Consumer",
    "CCL": "Consumer",
    "FLAIR": "Consumer",
    "SENCO": "Consumer",
    "DOMS": "Consumer",
    "SYMPHONY": "Consumer",
    "ORIENTELEC": "Consumer",
    "LAOPALA": "Consumer",
    "GOLDIAM": "Consumer",
    # Defence (14)
    "BEL": "Defence",
    "HAL": "Defence",
    "BDL": "Defence",
    "MAZDOCK": "Defence",
    "DATAPATTNS": "Defence",
    "BEML": "Defence",
    "GRSE": "Defence",
    "COCHINSHIP": "Defence",
    "DCAL": "Defence",
    "PARAS": "Defence",
    "CENTUM": "Defence",
    "IDEAFORGE": "Defence",
    "STEL": "Defence",
    "DCXINDIA": "Defence",
    # Diversified (7)
    "GRASIM": "Diversified",
    "GODREJIND": "Diversified",
    "3MINDIA": "Diversified",
    "BIRLACORPN": "Diversified",
    "DCMSHRIRAM": "Diversified",
    "ZUARI": "Diversified",
    "HINDWAREAP": "Diversified",
    # Education (3)
    "CLSEL": "Education",
    "NAVNETEDUL": "Education",
    "SCHAND": "Education",
    # Electronics (6)
    "DIXON": "Electronics",
    "SYRMA": "Electronics",
    "AVALON": "Electronics",
    "AMBER": "Electronics",
    "PGEL": "Electronics",
    "SBCL": "Electronics",
    # Energy (19)
    "RELIANCE": "Energy",
    "ONGC": "Energy",
    "BPCL": "Energy",
    "ADANIGREEN": "Energy",
    "IOC": "Energy",
    "GAIL": "Energy",
    "HINDPETRO": "Energy",
    "PETRONET": "Energy",
    "GUJGASLTD": "Energy",
    "CASTROLIND": "Energy",
    "SUZLON": "Energy",
    "ATGL": "Energy",
    "MRPL": "Energy",
    "MGL": "Energy",
    "IGL": "Energy",
    "OIL": "Energy",
    "CHENNPETRO": "Energy",
    "GSPL": "Energy",
    "GNFC": "Energy",
    # FMCG (28)
    "HINDUNILVR": "FMCG",
    "ITC": "FMCG",
    "NESTLEIND": "FMCG",
    "BRITANNIA": "FMCG",
    "DABUR": "FMCG",
    "TATACONSUM": "FMCG",
    "GODREJCP": "FMCG",
    "MARICO": "FMCG",
    "COLPAL": "FMCG",
    "UBL": "FMCG",
    "EMAMILTD": "FMCG",
    "PGHH": "FMCG",
    "GALAXYSURF": "FMCG",
    "HATSUN": "FMCG",
    "JYOTHYLAB": "FMCG",
    "BIKAJI": "FMCG",
    "VSTIND": "FMCG",
    "GODFRYPHLP": "FMCG",
    "RADICO": "FMCG",
    "EIDPARRY": "FMCG",
    "ZYDUSWELL": "FMCG",
    "KRBL": "FMCG",
    "LTFOODS": "FMCG",
    "DODLA": "FMCG",
    "HERITGFOOD": "FMCG",
    "VENKEYS": "FMCG",
    "VBL": "FMCG",
    "AVANTIFEED": "FMCG",
    # Finance (42)
    "BAJFINANCE": "Finance",
    "BAJAJFINSV": "Finance",
    "PFC": "Finance",
    "RECLTD": "Finance",
    "ABCAPITAL": "Finance",
    "MFSL": "Finance",
    "LICHSGFIN": "Finance",
    "SUNDARMFIN": "Finance",
    "MUTHOOTFIN": "Finance",
    "M&MFIN": "Finance",
    "MANAPPURAM": "Finance",
    "AAVAS": "Finance",
    "CHOLAFIN": "Finance",
    "ABSLAMC": "Finance",
    "IRFC": "Finance",
    "CANFINHOME": "Finance",
    "IIFL": "Finance",
    "MOTILALOFS": "Finance",
    "ANGELONE": "Finance",
    "PNBHOUSING": "Finance",
    "HUDCO": "Finance",
    "CRISIL": "Finance",
    "SBICARD": "Finance",
    "POONAWALLA": "Finance",
    "SHRIRAMFIN": "Finance",
    "BAJAJHLDNG": "Finance",
    "TATAINVEST": "Finance",
    "JMFINANCIL": "Finance",
    "EDELWEISS": "Finance",
    "CAMS": "Finance",
    "CDSL": "Finance",
    "KFINTECH": "Finance",
    "UTIAMC": "Finance",
    "BSE": "Finance",
    "MCX": "Finance",
    "CREDITACC": "Finance",
    "SPANDANA": "Finance",
    "FUSION": "Finance",
    "IREDA": "Finance",
    "HOMEFIRST": "Finance",
    "APTUS": "Finance",
    "MASFIN": "Finance",
    # Healthcare (13)
    "APOLLOHOSP": "Healthcare",
    "LALPATHLAB": "Healthcare",
    "MAXHEALTH": "Healthcare",
    "METROPOLIS": "Healthcare",
    "FORTIS": "Healthcare",
    "MEDPLUS": "Healthcare",
    "YATHARTH": "Healthcare",
    "RAINBOW": "Healthcare",
    "VIJAYA": "Healthcare",
    "KRSNAA": "Healthcare",
    "POLYMED": "Healthcare",
    "KIMS": "Healthcare",
    "THYROCARE": "Healthcare",
    # Hotels (5)
    "INDHOTEL": "Hotels",
    "LEMONTREE": "Hotels",
    "CHALET": "Hotels",
    "TAJGVK": "Hotels",
    "ORIENTHOT": "Hotels",
    # IT (45)
    "TCS": "IT",
    "INFY": "IT",
    "HCLTECH": "IT",
    "WIPRO": "IT",
    "TECHM": "IT",
    "NAUKRI": "IT",
    "PERSISTENT": "IT",
    "MPHASIS": "IT",
    "COFORGE": "IT",
    "OFSS": "IT",
    "LTTS": "IT",
    "KPITTECH": "IT",
    "TATAELXSI": "IT",
    "REDINGTON": "IT",
    "PAYTM": "IT",
    "AFFLE": "IT",
    "ZENSARTECH": "IT",
    "CYIENT": "IT",
    "ROUTE": "IT",
    "MASTEK": "IT",
    "HAPPSTMNDS": "IT",
    "NEWGEN": "IT",
    "INTELLECT": "IT",
    "RATEGAIN": "IT",
    "LATENTVIEW": "IT",
    "TANLA": "IT",
    "MAPMYINDIA": "IT",
    "NAZARA": "IT",
    "NIITLTD": "IT",
    "QUICKHEAL": "IT",
    "JUSTDIAL": "IT",
    "RSYSTEMS": "IT",
    "KSOLVES": "IT",
    "TRACXN": "IT",
    "ECLERX": "IT",
    "BSOFT": "IT",
    "TATATECH": "IT",
    "EMUDHRA": "IT",
    "DATAMATICS": "IT",
    "MSTCLTD": "IT",
    "NELCO": "IT",
    "AURIONPRO": "IT",
    "NUCLEUS": "IT",
    "SAKSOFT": "IT",
    "ONMOBILE": "IT",
    # Industrial (40)
    "SIEMENS": "Industrial",
    "HAVELLS": "Industrial",
    "ABB": "Industrial",
    "VOLTAS": "Industrial",
    "POLYCAB": "Industrial",
    "SOLARINDS": "Industrial",
    "CUMMINSIND": "Industrial",
    "CROMPTON": "Industrial",
    "BHARATFORG": "Industrial",
    "THERMAX": "Industrial",
    "HONAUT": "Industrial",
    "CARBORUNIV": "Industrial",
    "GRINDWELL": "Industrial",
    "TIMKEN": "Industrial",
    "VGUARD": "Industrial",
    "CGPOWER": "Industrial",
    "KAYNES": "Industrial",
    "LLOYDSME": "Industrial",
    "TIINDIA": "Industrial",
    "TRIVENI": "Industrial",
    "IONEXCHANG": "Industrial",
    "SJS": "Industrial",
    "GRAVITA": "Industrial",
    "FINPIPE": "Industrial",
    "ASTEC": "Industrial",
    "KIRLOSENG": "Industrial",
    "ELGIEQUIP": "Industrial",
    "ISGEC": "Industrial",
    "PRAJIND": "Industrial",
    "VOLTAMP": "Industrial",
    "TDPOWERSYS": "Industrial",
    "HITECHCORP": "Industrial",
    "STERTOOLS": "Industrial",
    "AIAENG": "Industrial",
    "GREAVESCOT": "Industrial",
    "NESCO": "Industrial",
    "ELECON": "Industrial",
    "RAJRATAN": "Industrial",
    "XPROINDIA": "Industrial",
    "PRECWIRE": "Industrial",
    # Infra (6)
    "ADANIENT": "Infra",
    "ADANIPORTS": "Infra",
    "GRINFRA": "Infra",
    "RITES": "Infra",
    "RVNL": "Infra",
    "BLS": "Infra",
    # Insurance (10)
    "SBILIFE": "Insurance",
    "HDFCLIFE": "Insurance",
    "ICICIPRULI": "Insurance",
    "NIACL": "Insurance",
    "STARHEALTH": "Insurance",
    "GICRE": "Insurance",
    "LICI": "Insurance",
    "ICICIGI": "Insurance",
    "POLICYBZR": "Insurance",
    "GODIGIT": "Insurance",
    # Logistics (9)
    "CONCOR": "Logistics",
    "DELHIVERY": "Logistics",
    "BLUEDART": "Logistics",
    "TCI": "Logistics",
    "ALLCARGO": "Logistics",
    "MAHLOG": "Logistics",
    "SNOWMAN": "Logistics",
    "GESHIP": "Logistics",
    "GATEWAY": "Logistics",
    # Media (11)
    "SUNTV": "Media",
    "ZEEL": "Media",
    "PVRINOX": "Media",
    "HATHWAY": "Media",
    "GTPL": "Media",
    "SAREGAMA": "Media",
    "SHEMAROO": "Media",
    "TVTODAY": "Media",
    "NDTV": "Media",
    "DEN": "Media",
    "NETWORK18": "Media",
    # Metals (21)
    "TATASTEEL": "Metals",
    "JSWSTEEL": "Metals",
    "HINDALCO": "Metals",
    "VEDL": "Metals",
    "SAIL": "Metals",
    "NMDC": "Metals",
    "HINDCOPPER": "Metals",
    "NATIONALUM": "Metals",
    "JSL": "Metals",
    "WELCORP": "Metals",
    "JINDALSTEL": "Metals",
    "SARDAEN": "Metals",
    "GALLANTT": "Metals",
    "NSLNISP": "Metals",
    "HINDZINC": "Metals",
    "MIDHANI": "Metals",
    "GPIL": "Metals",
    "SHYAMMETL": "Metals",
    "MAHSEAMLES": "Metals",
    "JINDALSAW": "Metals",
    "SUNFLAG": "Metals",
    # Mining (5)
    "COALINDIA": "Mining",
    "MOIL": "Mining",
    "KIOCL": "Mining",
    "GMDCLTD": "Mining",
    "NLCINDIA": "Mining",
    # Packaging (4)
    "APLLTD": "Packaging",
    "UFLEX": "Packaging",
    "HUHTAMAKI": "Packaging",
    "EPL": "Packaging",
    # Paints (5)
    "ASIANPAINT": "Paints",
    "BERGEPAINT": "Paints",
    "KANSAINER": "Paints",
    "INDIGOPNTS": "Paints",
    "SHALPAINTS": "Paints",
    # Paper (4)
    "TNPL": "Paper",
    "WSTCSTPAPR": "Paper",
    "JKPAPER": "Paper",
    "STARPAPER": "Paper",
    # Pharma (46)
    "SUNPHARMA": "Pharma",
    "CIPLA": "Pharma",
    "DRREDDY": "Pharma",
    "DIVISLAB": "Pharma",
    "TORNTPHARM": "Pharma",
    "LUPIN": "Pharma",
    "AUROPHARMA": "Pharma",
    "ALKEM": "Pharma",
    "IPCALAB": "Pharma",
    "BIOCON": "Pharma",
    "LAURUSLABS": "Pharma",
    "SYNGENE": "Pharma",
    "NATCOPHARM": "Pharma",
    "ZYDUSLIFE": "Pharma",
    "AJANTPHARM": "Pharma",
    "JBCHEPHARM": "Pharma",
    "GLAXO": "Pharma",
    "SPARC": "Pharma",
    "GLAND": "Pharma",
    "GLENMARK": "Pharma",
    "GRANULES": "Pharma",
    "ABBOTINDIA": "Pharma",
    "PFIZER": "Pharma",
    "ERIS": "Pharma",
    "MANKIND": "Pharma",
    "SUPRIYA": "Pharma",
    "IOLCP": "Pharma",
    "SOLARA": "Pharma",
    "CAPLIPOINT": "Pharma",
    "NEULANDLAB": "Pharma",
    "SHILPAMED": "Pharma",
    "AARTIDRUGS": "Pharma",
    "HIKAL": "Pharma",
    "ANURAS": "Pharma",
    "GUFICBIO": "Pharma",
    "JUBLPHARMA": "Pharma",
    "ASTRAZEN": "Pharma",
    "AARTIPHARM": "Pharma",
    "WINDLAS": "Pharma",
    "PPLPHARMA": "Pharma",
    "MARKSANS": "Pharma",
    "BLISSGVS": "Pharma",
    "SANOFI": "Pharma",
    "ORCHPHARMA": "Pharma",
    "RPSGVENT": "Pharma",
    "WOCKPHARMA": "Pharma",
    # Power (15)
    "NTPC": "Power",
    "POWERGRID": "Power",
    "TATAPOWER": "Power",
    "IEX": "Power",
    "NHPC": "Power",
    "SJVN": "Power",
    "JSWENERGY": "Power",
    "CESC": "Power",
    "GPPL": "Power",
    "TORNTPOWER": "Power",
    "ADANIPOWER": "Power",
    "RPOWER": "Power",
    "JPPOWER": "Power",
    "POWERMECH": "Power",
    "GIPCL": "Power",
    # Railways (3)
    "TITAGARH": "Railways",
    "TEXRAIL": "Railways",
    "RAILTEL": "Railways",
    # Realty (16)
    "DLF": "Realty",
    "OBEROIRLTY": "Realty",
    "PHOENIXLTD": "Realty",
    "PRESTIGE": "Realty",
    "GODREJPROP": "Realty",
    "BRIGADE": "Realty",
    "SOBHA": "Realty",
    "MAHLIFE": "Realty",
    "SUNTECK": "Realty",
    "KOLTEPATIL": "Realty",
    "PURVA": "Realty",
    "LODHA": "Realty",
    "RUSTOMJEE": "Realty",
    "SIGNATURE": "Realty",
    "ANANTRAJ": "Realty",
    "ARVSMART": "Realty",
    # Renewable (2)
    "BORORENEW": "Renewable",
    "INOXWIND": "Renewable",
    # Retail (7)
    "TRENT": "Retail",
    "ABFRL": "Retail",
    "NYKAA": "Retail",
    "DMART": "Retail",
    "SHOPERSTOP": "Retail",
    "VMART": "Retail",
    "GOCOLORS": "Retail",
    # Staffing (2)
    "TEAMLEASE": "Staffing",
    "QUESS": "Staffing",
    # Telecom (5)
    "BHARTIARTL": "Telecom",
    "IDEA": "Telecom",
    "TTML": "Telecom",
    "TATACOMM": "Telecom",
    "STLTECH": "Telecom",
    # Textiles (11)
    "ARVIND": "Textiles",
    "TRIDENT": "Textiles",
    "HIMATSEIDE": "Textiles",
    "DONEAR": "Textiles",
    "NITIRAJ": "Textiles",
    "SPAL": "Textiles",
    "RUPA": "Textiles",
    "LUXIND": "Textiles",
    "PGIL": "Textiles",
    "STYL": "Textiles",
    "KPRMILL": "Textiles",
    # Travel (4)
    "IRCTC": "Travel",
    "YATRA": "Travel",
    "EASEMYTRIP": "Travel",
    "IXIGO": "Travel",
}
